---
title: "็Homework 9"
author: "Pakorn Sagulkoo 6380064520"
date: "18/11/2563"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercise

1. Visualize by a transition graph the following transition matrices. For the process with four states take the names of the nucleotides in the order A, G, T, and C.

```{r}
library(diagram)
x1 <- matrix(c(1/3,3/4,2/3,1/4),nrow=2,byrow=F)
x2 <- matrix(c(1,0,0,1),nrow=2,byrow=F)
x3 <- matrix(c(0,1,1,0),nrow=2,byrow=F)
x4 <- matrix(c(1/4,1/6,0,1/8,2/4,2/6,2/7,1/8,0,2/6,5/7,2/8,1/4,1/6,0,4/8),nrow=4,byrow=F)
x5 <- matrix(c(1/4,1/6,0,0,3/4,5/6,0,0,0,0,5/7,3/8,0,0,2/7,5/8),nrow=4,byrow=F)
n_base <- c('A','G','T','C')
head_name <- list(n_base,n_base)
dimnames(x4) <- head_name
dimnames(x5) <- head_name
x1
x2
x3
x4
x5
par(mar=rep(3,4))
par(mfrow=c(2,3))
all_var <- list(x1,x2,x3,x4,x5)
for (i in 1:5){
  plotmat(all_var[[i]],relsize = 0.8, cex = 0.8)
}
```

2. Computing probabilities. Given the states 0 and 1 and the following initial distribution and probability matrix 
  
```{r}
p <- matrix(c(3/4,1/4,1/2,1/2),nrow=2,byrow=T)
pi_0 <- matrix(c(1/2,1/2),nrow=1,byrow=T)
```
  
  (a) Compute P(X1 = 0).
        
```{r}
pi_1 <- pi_0 %*% p
pi_1[1]
```
  (b) Compute P(X1 = 1).
  
```{r}
pi_1[2]
```
  (c) Compute P(X2 = 0|X0 = 0).
  
```{r}
pi_x0 <- c(1,0)
pi_st <- pi_x0 %*% p
pi_nd <- pi_st %*% p
pi_nd[1]
```
  (d) Compute P(X2 = 1|X0 = 0).
  
```{r}
pi_nd[2]
```
  
  
  
  
  
  
    